# Randomness
*In this lecture we will learn about randomness and pseudo-random numbers*

In [2]:
# Firstly we will import Numpy for generating numbers
import numpy as np

# Simulating a Coin Flip

The following code flips one coin, giving a 0 or a 1.

We can interpret a 1 as heads and a 0 as tails.

The probability of getting a 1 is 0.5.

This means the coin is fair - a 50/50 chance of heads/tails.


Probabilities are numbers between 0 and 1, inclusive.

If an event happens with probability 0, it means it has no chance of happening.

A 1 means it will definitely happen.

A probability of 0.1 means a 10% chance, 0.2 means a 20% chance, and so on.

Note: We will just use the np.random.binomial() function for now, ignoring what it might mean

In [4]:
# Flip a fair coin.
np.random.binomial(1, 0.5)

1

Note that every time we re-run this notebook we will get a new coin flip.

The result above is a 1 for me but might be a 0 for you.

That will happen throughout this notebook.

# Repeated Flips

A single coin flip is not very interesting.

How about we flip a fair coin 100 times?

We can supply a third parameter to the function, the 100.

In [6]:
# Flip a fair coin 100 times.
np.random.binomial(1, 0.5, 100)

array([0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1,
       0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0,
       1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1,
       1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0,
       1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0])

The outcome of each flip is represented by a 0 or a 1.

While it is interesting to see each flip, sometimes we only want to know the total number of heads.

If we delete the third parameter - the 100 - and change the first to 100, here's what happens.

In [7]:
# Flip a fair coin 100 times, giving only the total number of heads.
np.random.binomial(100, 0.5)

46

At the time of writing, the output above is 46.

Again, it might be (in fact, probably be) different for you.

Note that we have lost some detail having moved from a list of 0's and 1's to a single number representing the number of heads.

I do not know which 46 of the 100 coin flips came up heads.

It might have been the first 46, for all I know, with the last 54 coming up tails.

Indeed the probability of that is the same as the probability of any other sequence of 46 1's and 54 0's.

A lot of probability focuses on the relationship between actual events - seeing the list of underlying outcomes - and summaries of the events - seeing only the total number of heads, for instance.

# Twice 50/50
One hundred coin flips is lot - we will reduce it to ten coin flips for simplicity.

Sometimes when we ask numpy to flip ten coins, we'll get five heads.

The following code repeatedly flips 10 coins and prints out the first three times we get 5 heads.

In [12]:
# Keep flipping coins until we get three examples of getting five heads in ten coin tosses.

# Number of examples.
N = 3

# Keep track of number of arrays generated.
total_no = 0

# Keep trying until we get three examples.
while N > 0:
    # Add 1 to total.
    total_no = total_no + 1
    # Toss 10 coins.
    tosses = np.random.binomial(1, 0.5, 10)
    # Check if we got five heads.
    if tosses.sum() == 5:
        # If we got 5 heads, print the list of heads/tails.
        print(tosses)
        # Reduce the number of examples left to find by 1.
        N = N - 1

print(f'Total generated: {total_no}')

[0 0 0 1 1 0 0 1 1 1]
[0 1 0 0 0 1 1 0 1 1]
[0 1 1 0 1 1 0 1 0 0]
Total generated: 7


Listed above are three examples of ten fair coins being flipped.

Each 1 represents a head and each 0 a tail.

The three lists of ten 0's and 1's might be identical, but it is far more likely that at least one of them is different.

Indeed, it is most likely that all three are different from each other.

Here is what the output looks like for me at the time of writing.

[0 0 0 1 1 0 0 1 1 1]
[0 1 0 0 0 1 1 0 1 1]
[0 1 1 0 1 1 0 1 0 0]

The first coin flip in each list came up tails - the three 0's at the start of each line.

The second flip came up tails as well in the first example and heads in the other two examples.

Likewise, the third coin flip can up tails for the first and heads for the second and third in the last example.

They are all different but share a common property: there are five 1's, or five heads, in each set of ten coin flips.

How many other ways are there to flip ten coins and get five heads we will see in the next chapter

# Counting Heads
We could get numpy to keep flipping ten coins, tracking each time it gets five heads.

Eventually we would likely get all the possibilities, although we would also likely get some duplicates.

But how would we know when to stop flipping coins?

How would we know we had them all?

It would be better to have an analytical method for counting the number of possibilities - based on logic, on deduction.

I will try to convince you that the following calculation gives the number of possibilities.

In [14]:
(10 * 9 * 8 * 7 * 6) // (5 * 4 * 3 * 2 * 1)

252

This is a calculation involving the numbers 1 to 10, multiplication represented by the symbol * and division using the symbol /.

The parentheses here are just for grouping terms together to specify that the eight multiplications should happen before the single division.

Note: technically we should use // here instead of / in Python. The first divides integers, the second real numbers. We won't worry about that, though.

Let us look first at the first part of the calculation, 10 * 9 * 8 * 7 * 6.

This says multiply 10 by 9, then that by 8, then by 7, and finally by 6.

That's quite a big number.

In [15]:
10 * 9 * 8 * 7 * 6

30240

Here is the logic behind that part of the calculation.

We start out to flip ten coins, so let's put ten placeholders (_) for the ten outcomes.

_ _ _ _ _ _ _ _ _ _

Once we start flipping coins, each of the ten 0's or 1's generated will go in each placeholder in turn.

Suppose we flip the first coin and get a head.

Then the placeholders look like this:

1 _ _ _ _ _ _ _ _ _

Okay, so let's reset the placeholders and think about the different places we can put 1's.

_ _ _ _ _ _ _ _ _ _

Remember we need exactly five 1's at the end - we need five placeholders containing 1's.

Imagine you are numpy - you have to pick the five placeholders that will contain 1's.

How many options do you have?

Well, for the first 1, you can put it in the first placeholder, or the second, or any of the other eight.

So you have ten choices - hence the 10 in the calculation above.

Once you pick a location for the first 1, you have nine available placeholders left.

So for the second 1 you need to place somewhere, you have 9 choices - hence the 9 in the above calculation.

For the third 1, you have eight choices, for the fourth you have seven, and for the fifth 1 you are left with six choices.

Once you place your sixth 1, all choice is gone - you have to put 0's in the remaining five placeholders so that you have exactly five 1's.

Now, why multiply these numbers together as opposed to add them or something else?

Well, for each choice of ten placeholders for the first 1, there are nine choices for the second 1.

It is the for each that is important here - it implies we should multiply.

Let us list all of the posibilities for positions of the first and second 1's to get the idea.

In [17]:
# Number of combinations.
no_combs = 0

# Select the first position.
for first in [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]:
    # Select the position for the second position.
    for second in [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]:
        # Make sure the first and second positions are different.
        if not first == second:
            # Print the combination.
            print(f'({first:2},{second:2})')
            # Add one to number of combinations.
            no_combs = no_combs + 1

# Print total number of combinations.
print(f'Total combinations is {no_combs}.')

( 1, 2)
( 1, 3)
( 1, 4)
( 1, 5)
( 1, 6)
( 1, 7)
( 1, 8)
( 1, 9)
( 1,10)
( 2, 1)
( 2, 3)
( 2, 4)
( 2, 5)
( 2, 6)
( 2, 7)
( 2, 8)
( 2, 9)
( 2,10)
( 3, 1)
( 3, 2)
( 3, 4)
( 3, 5)
( 3, 6)
( 3, 7)
( 3, 8)
( 3, 9)
( 3,10)
( 4, 1)
( 4, 2)
( 4, 3)
( 4, 5)
( 4, 6)
( 4, 7)
( 4, 8)
( 4, 9)
( 4,10)
( 5, 1)
( 5, 2)
( 5, 3)
( 5, 4)
( 5, 6)
( 5, 7)
( 5, 8)
( 5, 9)
( 5,10)
( 6, 1)
( 6, 2)
( 6, 3)
( 6, 4)
( 6, 5)
( 6, 7)
( 6, 8)
( 6, 9)
( 6,10)
( 7, 1)
( 7, 2)
( 7, 3)
( 7, 4)
( 7, 5)
( 7, 6)
( 7, 8)
( 7, 9)
( 7,10)
( 8, 1)
( 8, 2)
( 8, 3)
( 8, 4)
( 8, 5)
( 8, 6)
( 8, 7)
( 8, 9)
( 8,10)
( 9, 1)
( 9, 2)
( 9, 3)
( 9, 4)
( 9, 5)
( 9, 6)
( 9, 7)
( 9, 8)
( 9,10)
(10, 1)
(10, 2)
(10, 3)
(10, 4)
(10, 5)
(10, 6)
(10, 7)
(10, 8)
(10, 9)
Total combinations is 90.


So, we see that when we have 10 choices for the first 1 and 9 for the second, we should multiply 10 and 9 to get the total number of combinations.

Now, let us work out the second part of the calculation: 5 * 4 * 3 * 2 * 1.

There is a clue in the output above.

The first line says "( 1, 2)"

That looks like this:

1 1 _ _ _ _ _ _ _ _

Now the tenth line is "( 2, 1)", which looks like this:

1 1 _ _ _ _ _ _ _ _

They're the same outcome - we have double counted it.

In fact, if you inspect the list of all 90 combinations, you'll see that every outcome is counted twice.

Hence, we need to divide the 90 by 2, to get 45 distinct placements of the first two 1's.

Now, for each of those 45 placements of the first two 1's, we are going to triple count the placement of the third 1, so we have to divide by 3.

There are too many possibilities to print, but look at this example.
Let's use this example of 1 placements:

1 _ _ 1 _ 1 _ _ _ _

That can come from placing the third 1 in the correct position for each of these placements of two 1':

1 _ _ 1 _ _ _ _ _ _ (Place the third 1 in the sixth placeholder.)

1 _ _ _ _ 1 _ _ _ _ (Place the third 1 in the fourth placeholder.)

_ _ _ 1 _ 1 _ _ _ _ (Place the third 1 in the first placeholder.)

Likewise we will count each placement of the fourth 1 four times, and the fifth 1 five times.

Thus we need to divide by both 4 and 5.

Note the multiplication by 1 at the end is unnecessary - it just makes the formula look a big nicer.

This gives division by 5 * 4 * 3 * 2 * 1.

## Exercise 1 

Is somewhat interesting that (5 * 4 * 3 * 2 * 1) perfectly divides (10 * 9 * 8 * 7 * 6) - there's no remainder.

If we only wanted exactly four heads as opposed to five, the equivalent calculation would be (10 * 9 * 8 * 7) / (4 * 3 * 2 * 1).

Does that evenly divide too? What is the formula in general?

Does it always come out as a positive whole number?

## Answer

# The Binomial Distribution
The usual notation is:
p = probability of success,
q = probability of failure = 1 - p.

Note that p + q = 1. 

In statistical terms, A Bernoulli trial is each repetition of an experiment
involving only 2 outcomes.
We are often interested in the result of independent, repeated bernoulli trials, i.e. the number of
successes in repeated trials.

1. independent - the result of one trial does not affect the result of another trial
2. repeated - conditions are the same for each trial, i.e. p and q remain constant across trials. 

Hayes refers to this as a stationary process. If p and q can change from trial to trial,
the process is nonstationary. The term identically distributed is also often used.

A binomial distribution gives us the probabilities associated with independent, repeated
Bernoulli trials. In a binomial distribution the probabilities of interest are those of receiving
a certain number of successes, r, in n independent trials each having only two possible
outcomes and the same probability, p, of success. 
So, we can determine the probability of getting 4 heads in 10 coin tosses.
How does the binomial distribution do this? Basically, a two part process is involved. First, we
have to determine the probability of one possible way the event can occur, and then determine
the number of different ways the event can occur. 

P(Event) = (Number of ways event can occur) * P(One occurrence).

In this case, we’ll call getting a heads a “success.” Also, in this case, n = 10, the number of successes is
r = 4, and the number of failures (tails) is n – r = 10 – 4 = 6. One way this can occur is if the first
4 tosses are heads and the last 6 are tails, i.e.

S S S S F F F F F F
The likelihood of this occurring is
P(S) * P(S) * P(S) * P(S) * P(F) * P(F) * P(F) * P(F) * P(F) * P(F)

More generally, if p = probability of success and q = 1 – p = probability of failure, the
probability of a specific sequence of outcomes where there are r successes and n-r failures is:

$P^r Q^n-^r$

In this particular case, p = q = .5, r = 4, n-r = 6, so the probability of 4 straight heads followed
by 6 straight tails is $.5^4$ $.5^6$ = 0.0009765625 (or 1 out of 1024)

Are binomial distributions always positive?

Whenever p = 0.5, the binomial distribution will be symmetrical, regardless of how large or small the value of n. However, when p ≠ 0.5, the distribution will be skewed. If p < 0.5, the distribution will be positive or right skewed. If p > 0.5, the distribution will be negative or left skewed.

## Exercise 2

Note that there are the same number of ways to get 4 tails as there to get 4 heads. Explain why this is.

## Answer

# Resources:
1.https://www3.nd.edu/~rwilliam/stats1/x13.pdf

2.https://www.oreilly.com/library/view/statistics-for-six/0132291959/0132291959_ch05lev2sec3.html